### ISSUE TITLE
Missing something?

### ISSUE THREAD

**Issue by CesarCastellonE** [thomdixon/pysha2#6]
Hello, 
I used your code to hash the variable a
a= "00baf6626abc2df808da36a518c69f09b0d2ed0a79421ccfde4f559d2e42128"  {#b"# CHAINS SHORTER at 2128_ }
and it gives the correct value (compared to hashlib),
but if I try to hash 
a= "00baf6626abc2df808da36a518c69f09b0d2ed0a79421ccfde4f559d2e42128b" it provides a wrong hash value, got lost on the code so I thought I'd better ask you.
I am intending to use your code two 64 char concatenated variables.

Thanks a lot for your comments.

**Comment by CesarCastellonE** [comment]
Sorry, my mistake.. I was trying to comment on https://gist.github.com/prokls/41e82472bd4968720d1482f81235e0ac#file-pysha2-sha2-sha256-py.

**Comment by thomdixon** [comment]
Howdy! I'm a little confused, as I get the same value hashing `a` above:

```python
>>> from hashlib import sha256 as hl_sha256
>>> from sha2 import sha256 as py_sha256
>>>
>>> x = '00baf6626abc2df808da36a518c69f09b0d2ed0a79421ccfde4f559d2e42128'
>>> hl_sha256(x).hexdigest() == py_sha256(x).hexdigest()
True
>>> hl_sha256(x+'b').hexdigest() == py_sha256(x+'b').hexdigest()
True
>>> 
```

**Comment by CesarCastellonE** [comment]
This program you are using is python27 correct? is there any version for python3?

**Comment by thomdixon** [comment]
> Sorry, my mistake.. I was trying to comment on https://gist.github.com/prokls/41e82472bd4968720d1482f81235e0ac#file-pysha2-sha2-sha256-py.

Oh okay. I'll go ahead and close this then. Good luck!

**Comment by thomdixon** [comment]
> This program you are using is python27 correct? is there any version for python3?

Yep! There's no version for Python 3. Since `hashlib` exists, I figured that it wasn't worth porting (I originally wrote this for Python 2.3 and 2.4).

**Comment by thomdixon** [comment]
If you need an alternative version of SHA256, it might be worth trying the Cryptography library: https://cryptography.io/en/latest/.

**Comment by CesarCastellonE** [comment]
The link I provided takes you to someone's program who said he used your code as a reference. I am so sorry for disturbing you with my messages and you were really kind answering them, but would it be too much if you could give that link (https://gist.github.com/prokls/41e82472bd4968720d1482f81235e0ac) a look? I am a Python newbie that got into this because of my research work at my university, Any help would be much appreciated.

**Comment by thomdixon** [comment]
> The link I provided takes you to someone's program who said he used your code as a reference. I am so sorry for disturbing you with my messages and you were really kind answering them, but would it be too much if you could give that link (https://gist.github.com/prokls/41e82472bd4968720d1482f81235e0ac) a look? I am a Python newbie that got into this because of my research work at my university, Any help would be much appreciated.

Sure. This seems to be an issue in how they process the buffer for updates (likely an off-by-1 error or similar). Here's a gist that should work: https://gist.github.com/thomdixon/af7c84e94ac608142b497a4dfc8339fe

Cheers!

**Comment by CesarCastellonE** [comment]
Thanks a lot!, it is working now. Cheers!
